// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE3Odj9ZieCq6xBokZaB_2SHADPM0-lYw',
    appId: '1:581500965224:web:4cf542f759e2c3572586dd',
    messagingSenderId: '581500965224',
    projectId: 'cp-courses-23c42',
    authDomain: 'cp-courses-23c42.firebaseapp.com',
    storageBucket: 'cp-courses-23c42.appspot.com',
    measurementId: 'G-Z84RXC1JMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRgH2qwF8l3ix_USuJRyhxQTQQNCuq0jk',
    appId: '1:581500965224:android:6f4e6a7db1e5bafc2586dd',
    messagingSenderId: '581500965224',
    projectId: 'cp-courses-23c42',
    storageBucket: 'cp-courses-23c42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZyN3HwY5M74ZAUjUc5_S1rEvLRU3FkYw',
    appId: '1:581500965224:ios:d6edb928d4fe584d2586dd',
    messagingSenderId: '581500965224',
    projectId: 'cp-courses-23c42',
    storageBucket: 'cp-courses-23c42.appspot.com',
    iosBundleId: 'com.example.cpCourses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZyN3HwY5M74ZAUjUc5_S1rEvLRU3FkYw',
    appId: '1:581500965224:ios:a4935e6cb518c5b52586dd',
    messagingSenderId: '581500965224',
    projectId: 'cp-courses-23c42',
    storageBucket: 'cp-courses-23c42.appspot.com',
    iosBundleId: 'com.example.cpCourses.RunnerTests',
  );
}
